### ISSUE TITLE
Documentation Upgrade

### ISSUE THREAD

**Issue by dmcennis** [abego/guitesting-swing#3]
In order to run guitesting-swing in semeru-18 (IBM's version of the JDK 18), the option '--add-opens=java.desktop/sun.awt=ALL-UNNAMED' should be added to the jvm arguments when launching tests from this kit. This prevents an exception about exports from sun.awt to unnamed modules.

**Comment by abego** [comment]
Hi Daniel, thanks for sharing this information.

I added it to the project's README, also giving you credit.
